name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Running UI Testing
      run: xcodebuild test -project "Rilabs UITesting".xcodeproj -scheme "Rilabs UITesting" -destination "platform=iOS Simulator,name=iPhone 11 Pro"
    - name: Build iOS App
      run: xcodebuild -project "Rilabs UITesting".xcodeproj -scheme "Rilabs UITesting" -destination "platform=iOS Simulator,name=iPhone 11 Pro"
